sudo: required
services:
  - docker

language: cpp
addons:
  apt:
    packages:
      - python3

env:
  matrix:
    - MATRIX_EVAL="CXX=g++ && CXX_VERSION=5"
    # g++ 5 and 6 are couldn't be installed.
    # - CXX=g++ CXX_VERSION="6"
    # - CXX=g++ CXX_VERSION="7"
    - MATRIX_EVAL="CXX=clang++ && CXX_VERSION=3.8"
    - MATRIX_EVAL="CXX=clang++ && CXX_VERSION=3.9"
    - MATRIX_EVAL="CXX=clang++ && CXX_VERSION=4.0"
    - MATRIX_EVAL="CXX=clang++ && CXX_VERSION=5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $CXX
  - echo $CXX_VERSION
  - docker pull ubuntu:xenial
  - docker run -d --name xenial -v $PWD:/travis ubuntu:xenial tail -f /dev/null
  - docker ps

install:
  - docker exec -t xenial bash -c "export CXX=$CXX;
    export CXX_VERSION=$CXX_VERSION;
    apt-get update;
    apt-get install -y python3;
    apt-get install -y wget;
    apt-get install -y unzip;
    apt-get install -y build-essential;
    add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    if [[ \"$CXX\" == \"clang++\" ]]; then
      apt-get install -y software-properties-common;
      add-apt-repository llvm-toolchain-xenial-$CXX_VERSION;
    fi;
    apt-get update;
    if [[ \"$CXX\" == \"clang++\" ]]; then
      apt-get install -y clang-$CXX_VERSION;
    elif [[ \"$CXX\" == \"g++\" ]]; then
      apt-get install -y g++-$CXX_VERSION;
    fi"

script:
  - docker exec -t xenial bash -c "cd /travis;
    export CXX=$CXX-$CXX_VERSION;
    export CXX_VERSION=$CXX_VERSION;
    echo $CXX;
    ./configure.py && make && make test;"
