//  This file generated automatically using 'ucd-tool.py'.
//  You can find the author and the copyright in file 'tools/ucd-tool.py'.
//
//  Word_Break (WB) table.
#include "wb.h"
#include <seshat/unicode/version.h>
#include <seshat/utils.h>

namespace seshat {
namespace unicode {
namespace ucd {

static_assert(UnicodeVersion == (Version { 10, 0, 0 }), "Version error");


static const uint8_t stage_1[] = {
    0, 1, 2, 2, 2, 2, 2, 2,
    2, 2, 3, 4, 2, 2, 2, 5,
    2, 2, 2, 6, 7, 8, 9, 2,
    10, 11, 2, 12, 13, 14, 15, 16,
    17, 18, 19, 20, 21, 22, 23, 24,
    25, 26, 27, 28, 29, 30, 31, 32,
    33, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 34, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    35, 36, 37, 2, 38, 2, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 2,
    2, 48, 49, 2, 2, 2, 2, 2,
    2, 50, 51, 52, 2, 53, 2, 2,
    2, 54, 55, 56, 57, 58, 59, 2,
    60, 58, 58, 61, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 62, 63, 64, 65, 2, 2,
    66, 67, 68, 69, 70, 71, 72, 73,
    2, 2, 2, 74, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 75, 76, 2, 2, 2,
    2, 2, 2, 2, 2, 77, 2, 2,
    78, 79, 80, 2, 2, 2, 81, 2,
    82, 83, 2, 2, 2, 84, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 85, 86, 87, 2, 2, 2, 2,
    88, 89, 90, 91, 92, 93, 94, 2,
    95, 96, 97, 98, 99, 100, 101, 102,
    103, 104, 105, 106, 2, 107, 108, 109,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 110, 111,
    2, 112, 113, 2, 114, 115, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 116, 3, 3, 117,
    2, 2, 118, 119, 120, 2, 2, 121,
    122, 123, 3, 3, 3, 3, 
};

static const TwoStageTable<Wb, uint8_t, 64>::BlockArray stage_2[] = {
  // Block 0
  {
    Wb::LF, Wb::NL, Wb::NL, Wb::CR, Wb::DQ, Wb::SQ, Wb::MN, Wb::MB,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::ML, Wb::MN, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::EX, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 1
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::NL, Wb::LE, Wb::FO, Wb::LE, Wb::ML, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 2
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 3
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 4
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::MN, Wb::LE, Wb::LE, Wb::ML, Wb::LE,
  },
  // Block 5
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 6
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::MN, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 7
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
  },
  // Block 8
  {
    Wb::HL, Wb::HL, Wb::LE, Wb::ML, Wb::FO, Wb::FO, Wb::FO, Wb::FO,
    Wb::FO, Wb::FO, Wb::MN, Wb::MN, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::FO,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 9
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::MN, Wb::LE, Wb::LE, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 10
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::FO, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::FO, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 11
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 12
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 13
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::MN, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 14
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 15
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::FO, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 16
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 17
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 18
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 19
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
  },
  // Block 20
  {
    Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 21
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 22
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 23
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 24
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::NU,
  },
  // Block 25
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE,
  },
  // Block 26
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 27
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE,
  },
  // Block 28
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 29
  {
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 30
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 31
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 32
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 33
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 34
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 35
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 36
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 37
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::FO, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 38
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 39
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 40
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 41
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 42
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 43
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 44
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 45
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::LE, Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
  },
  // Block 46
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 47
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 48
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 49
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 50
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::ZWJ, Wb::FO, Wb::FO,
    Wb::MB, Wb::MB, Wb::MB, Wb::ML, Wb::NL, Wb::NL, Wb::FO, Wb::FO,
  },
  // Block 51
  {
    Wb::FO, Wb::FO, Wb::FO, Wb::EX, Wb::EX, Wb::EX, Wb::MN, Wb::EX,
    Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO,
    Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 52
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 53
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::EB, Wb::GAZ, Wb::GAZ, Wb::GAZ, Wb::GAZ, Wb::EB,
    Wb::GAZ, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::GAZ, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 54
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 55
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 56
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 57
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
  },
  // Block 58
  {
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
  },
  // Block 59
  {
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 60
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
  },
  // Block 61
  {
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 62
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 63
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 64
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 65
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 66
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 67
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 68
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 69
  {
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 70
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 71
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
  },
  // Block 72
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 73
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
  },
  // Block 74
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 75
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::HL, Wb::Extend, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
    Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL, Wb::HL,
  },
  // Block 76
  {
    Wb::HL, Wb::HL, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 77
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::MN, Wb::ML, Wb::MN, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::EX, Wb::EX, Wb::EX, Wb::EX,
    Wb::EX, Wb::MN, Wb::MB, Wb::MN, Wb::ML, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 78
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::FO, Wb::MB, Wb::MN, Wb::MB, Wb::ML, Wb::MN, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::EX, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 79
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::KA,
    Wb::KA, Wb::KA, Wb::KA, Wb::KA, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
  },
  // Block 80
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::FO, Wb::FO, Wb::FO, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 81
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::LE,
  },
  // Block 82
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 83
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 84
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 85
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 86
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 87
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 88
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 89
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 90
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::FO, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::NU,
  },
  // Block 91
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU,
  },
  // Block 92
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 93
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE,
  },
  // Block 94
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 95
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 96
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 97
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
  },
  // Block 98
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 99
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 100
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 101
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 102
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 103
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 104
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 105
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 106
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 107
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 108
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 109
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::LE, Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 110
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 111
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 112
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 113
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::KA, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 114
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::FO, Wb::FO,
    Wb::FO, Wb::FO, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 115
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::FO, Wb::FO, Wb::FO,
    Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::FO, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 116
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
    Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::Extend, Wb::Extend, Wb::Extend,
  },
  // Block 117
  {
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 118
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 119
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU, Wb::NU,
  },
  // Block 120
  {
    Wb::NU, Wb::NU, Wb::NU, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
  },
  // Block 121
  {
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE,
    Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::LE, Wb::RI, Wb::RI,
    Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI,
    Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI,
    Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI, Wb::RI,
    Wb::GAZ, Wb::GAZ, Wb::GAZ, Wb::EB, Wb::GAZ, Wb::GAZ, Wb::GAZ, Wb::EB,
  },
  // Block 122
  {
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::GAZ, Wb::GAZ,
    Wb::EM, Wb::EM, Wb::EM, Wb::EM, Wb::EM, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EBG, Wb::EBG, Wb::EBG, Wb::EBG, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::GAZ,
    Wb::EB, Wb::GAZ, Wb::GAZ, Wb::GAZ, Wb::GAZ, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::GAZ, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
  },
  // Block 123
  {
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::GAZ, Wb::GAZ, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB,
    Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::EB, Wb::FO, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
    Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend, Wb::Extend,
  },

};

const TwoStageTable<Wb, uint8_t, 64> wb_table(
    stage_1, sizeof(stage_1) / sizeof(uint8_t), // 494
    stage_2, sizeof(stage_2) / (64 * sizeof(Wb))); // 124


Wb wb(uint32_t cp)
{
    return wb_table.at(cp);
}

} // namespace ucd
} // namespace unicode
} // namespace seshat
